### ISSUE TITLE
Option to not add the date?

### ISSUE THREAD

**Issue by seqizz** [firecat53/todotxtmenu#2]
Hi there,

That seems like a really simple useful project, thanks.

Is it possible to just add a line, without prepending the date? Manually added tasks seem to be working without issues, but adding via rofi always adds the date.

Thanks

**Comment by firecat53** [comment]
I can take a look at adding an option to toggle using the date. Thanks for the interest!

**Comment by firecat53** [comment]
Done! Added `-no-created-date` option. Let me know if that works for you.

**Comment by seqizz** [comment]
Yep, works great :+1: Thanks.

> I was using the release binary before, and realized there is a small difference on task creation on main branch. Now it feels easier to just input the title directly, so it might be good to release a new version :slightly_smiling_face:

**Comment by firecat53** [comment]
v1.2.0 released. Thanks for the prompt!
