### ISSUE TITLE
Entering an element removes its title

### ISSUE THREAD

**Issue by seqizz** [firecat53/todotxtmenu#3]
Hi again,

Sorry for frequent issues :smile: 

When I enter an item to see its details, and go back via Esc, it removes its title. Tags and creation date stays there though (if the item had none, it becomes a blank line and gets removed on next execution).

**Comment by firecat53** [comment]
Yeah, sorry about that! Found that just before bed last night and it's fixed in the latest commit. I've got one other issue to fix as well and then I'll push a new release.

**Comment by firecat53** [comment]
Fixed and new release published. Hopefully everything works now!

**Comment by seqizz** [comment]
Yep, thanks for the fast fix :rocket:
